import React, { useRef, useState } from 'react';
import {
    Bold, Italic, List, Link as LinkIcon, Image as ImageIcon,
    Code, Heading1, Heading2, Quote, Wand2
} from 'lucide-react';
import { generateImage } from '../services/aiService';

interface RichTextEditorProps {
    value: string;
    onChange: (value: string) => void;
    onImageUpload: (e: React.ChangeEvent<HTMLInputElement>) => void;
}

const RichTextEditor: React.FC<RichTextEditorProps> = ({ value, onChange, onImageUpload }) => {
    const textareaRef = useRef<HTMLTextAreaElement>(null);
    const [showImagePrompt, setShowImagePrompt] = useState(false);
    const [imagePrompt, setImagePrompt] = useState('');
    const [isGeneratingImage, setIsGeneratingImage] = useState(false);

    const insertFormat = (startTag: string, endTag: string = '') => {
        const textarea = textareaRef.current;
        if (!textarea) return;

        const start = textarea.selectionStart;
        const end = textarea.selectionEnd;
        const text = textarea.value;
        const before = text.substring(0, start);
        const selection = text.substring(start, end);
        const after = text.substring(end);

        const newText = before + startTag + selection + endTag + after;
        onChange(newText);

        // Restore focus and selection
        setTimeout(() => {
            textarea.focus();
            const newCursorPos = start + startTag.length + selection.length + endTag.length;
            textarea.setSelectionRange(newCursorPos, newCursorPos);
        }, 0);
    };

    const handleGenerateImage = async () => {
        if (!imagePrompt) return;

        setIsGeneratingImage(true);
        try {
            const imageUrl = await generateImage(imagePrompt);
            const imageHtml = `
<figure class="my-8">
    <img src="${imageUrl}" alt="${imagePrompt}" class="w-full rounded-xl shadow-2xl border border-gray-700/50 hover:scale-[1.01] transition-transform duration-500" />
    <figcaption class="text-center text-sm text-primary mt-3 font-mono">
        <span class="opacity-75">Generated by NanoBanana Pro</span> • Prompt: "${imagePrompt}"
    </figcaption>
</figure>
`;
            insertFormat(imageHtml);
            setShowImagePrompt(false);
            setImagePrompt('');
        } catch (error) {
            console.error("Image generation failed", error);
            alert("Failed to generate image.");
        } finally {
            setIsGeneratingImage(false);
        }
    };

    const handleMagicFix = () => {
        // Mock AI functionality
        const fixes = [
            "Enhanced clarity and tone.",
            "Fixed grammar and punctuation.",
            "Optimized for SEO.",
            "Made the content more engaging."
        ];
        alert(`✨ Magic Fix Applied: ${fixes[Math.floor(Math.random() * fixes.length)]}`);
    };

    return (
        <div className="border border-gray-600 rounded-lg overflow-hidden bg-background-dark relative">
            {/* Image Generation Modal/Popover */}
            {showImagePrompt && (
                <div className="absolute top-14 left-2 z-50 bg-surface-dark border border-gray-600 p-4 rounded-xl shadow-2xl w-80 animate-in fade-in zoom-in duration-200">
                    <h4 className="text-sm font-bold text-white mb-2 flex items-center gap-2">
                        <Wand2 size={14} className="text-yellow-400" /> NanoBanana Pro
                    </h4>
                    <textarea
                        value={imagePrompt}
                        onChange={(e) => setImagePrompt(e.target.value)}
                        placeholder="Describe the image you want..."
                        className="w-full bg-background-dark border border-gray-700 rounded-lg p-2 text-xs text-white mb-3 focus:ring-1 focus:ring-yellow-400 outline-none resize-none"
                        rows={3}
                        autoFocus
                    />
                    <div className="flex justify-end gap-2">
                        <button
                            onClick={() => setShowImagePrompt(false)}
                            className="px-3 py-1.5 text-xs text-gray-400 hover:text-white transition-colors"
                        >
                            Cancel
                        </button>
                        <button
                            onClick={handleGenerateImage}
                            disabled={isGeneratingImage}
                            className="px-3 py-1.5 bg-yellow-500/20 text-yellow-400 border border-yellow-500/50 hover:bg-yellow-500/30 rounded-lg text-xs font-bold transition-all flex items-center gap-2"
                        >
                            {isGeneratingImage ? 'Generating...' : 'Generate Art'}
                        </button>
                    </div>
                </div>
            )}

            {/* Toolbar */}
            <div className="flex flex-wrap items-center gap-1 p-2 border-b border-gray-700 bg-surface-dark">
                <button onClick={() => insertFormat('**', '**')} className="p-1.5 text-gray-400 hover:text-white hover:bg-gray-700 rounded transition-colors" title="Bold">
                    <Bold size={16} />
                </button>
                <button onClick={() => insertFormat('*', '*')} className="p-1.5 text-gray-400 hover:text-white hover:bg-gray-700 rounded transition-colors" title="Italic">
                    <Italic size={16} />
                </button>
                <div className="w-px h-4 bg-gray-700 mx-1" />
                <button onClick={() => insertFormat('# ')} className="p-1.5 text-gray-400 hover:text-white hover:bg-gray-700 rounded transition-colors" title="Heading 1">
                    <Heading1 size={16} />
                </button>
                <button onClick={() => insertFormat('## ')} className="p-1.5 text-gray-400 hover:text-white hover:bg-gray-700 rounded transition-colors" title="Heading 2">
                    <Heading2 size={16} />
                </button>
                <div className="w-px h-4 bg-gray-700 mx-1" />
                <button onClick={() => insertFormat('- ')} className="p-1.5 text-gray-400 hover:text-white hover:bg-gray-700 rounded transition-colors" title="Bullet List">
                    <List size={16} />
                </button>
                <button onClick={() => insertFormat('> ')} className="p-1.5 text-gray-400 hover:text-white hover:bg-gray-700 rounded transition-colors" title="Quote">
                    <Quote size={16} />
                </button>
                <button onClick={() => insertFormat('```\n', '\n```')} className="p-1.5 text-gray-400 hover:text-white hover:bg-gray-700 rounded transition-colors" title="Code Block">
                    <Code size={16} />
                </button>
                <div className="w-px h-4 bg-gray-700 mx-1" />
                <button onClick={() => insertFormat('[', '](url)')} className="p-1.5 text-gray-400 hover:text-white hover:bg-gray-700 rounded transition-colors" title="Link">
                    <LinkIcon size={16} />
                </button>
                <label className="p-1.5 text-gray-400 hover:text-white hover:bg-gray-700 rounded transition-colors cursor-pointer" title="Upload Image">
                    <ImageIcon size={16} />
                    <input type="file" accept="image/*" multiple onChange={onImageUpload} className="hidden" />
                </label>

                <button
                    onClick={() => setShowImagePrompt(!showImagePrompt)}
                    className={`p-1.5 rounded transition-colors ${showImagePrompt ? 'bg-yellow-500/20 text-yellow-400' : 'text-gray-400 hover:text-yellow-400 hover:bg-gray-700'}`}
                    title="Generate with NanoBanana Pro"
                >
                    <Wand2 size={16} />
                </button>

                <div className="flex-grow" />

                <button
                    onClick={handleMagicFix}
                    className="flex items-center gap-1 px-2 py-1 text-xs font-medium text-cyan-400 bg-cyan-400/10 hover:bg-cyan-400/20 border border-cyan-400/30 rounded transition-all"
                >
                    <Wand2 size={12} />
                    Magic Fix
                </button>
            </div>

            {/* Editor Area */}
            <textarea
                ref={textareaRef}
                value={value}
                onChange={(e) => onChange(e.target.value)}
                className="w-full h-96 p-4 bg-transparent text-gray-200 focus:outline-none font-mono text-sm resize-y"
                placeholder="Write your masterpiece..."
            />

            <div className="px-3 py-1 bg-surface-dark border-t border-gray-700 text-xs text-gray-500 flex justify-between">
                <span>Markdown & HTML supported</span>
                <span>{value.length} chars</span>
            </div>
        </div>
    );
};

export default RichTextEditor;
